### ISSUE TITLE
TASK 1 : 예약 가능한 날짜 조회 API

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#11]
# Issue : 예약 가능한 날짜 조회 API
: 예약 가능한 날짜 목록을 반환하는 API

### TODO
- [ ] API 엔드포인트 정의 
- [ ] 데이터베이스에서 예약 가능한 날짜 목록 조회 로직 구현
- [ ] 단위 테스트 작성

### 개발공수
- 

### 결과물
- 예약 가능한 날짜 조회 API 및 테스트 코드
