### ISSUE TITLE
TASK 2 : 특정 날짜의 좌석 상태 조회 API

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#12]
# Issue : 특정 날짜의 좌석 상태 조회 API
: 특정 날짜의 예약 가능한 좌석 정보를 반환하는 API

### TODO
- [ ] API 엔드포인트 정의 (GET /seats/available?date={date})
- [ ] DB에서 좌석 상태 조회 로직 구현
- [ ] 단위 테스트 작성

### 개발공수
- ?? M/D

### 결과물
- 좌석 상태 조회 API 및 테스트 코드
