### ISSUE TITLE
TASK 1 : 좌석 예약 요청 API

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#13]
# Issue : 좌석 예약 요청 API
: 사용자의 좌석 예약 요청을 처리 후 좌석 임시 배정

### TODO
- [ ] API 엔드포인트 정의 (POST /seats/reserve)
- [ ] 요청 파라미터 검증 (사용자 ID, 날짜, 좌석 번호)
- [ ] 임시 예약 로직 호출
- [ ] 단위 테스트 작성

### 개발공수
-
### 결과물
- 좌석 예약 요청 API 및 테스트 코드
