### ISSUE TITLE
TASK 2 :  임시 예약(시간 제한) 로직 개발

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#14]
# Issue : 임시 예약(시간 제한) 로직
: 좌석을 특정 시간 동안 임시로 배정하고, 시간이 초과되면 상태를 해제

### TODO
- [ ] 시간 제한 로직 구현
- [ ] 좌석 상태 처리
- [ ] 단위 테스트 작성

### 개발공수
-

### 결과물
- 임시 예약 로직 및 테스트 코드
