### ISSUE TITLE
TASK 3 : 동시성 제어 로직 개발

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#15]
# Issue : 동시성 제어 로직
: 동일한 좌석이 여러 사용자에게 중복 배정되지 않도록 제어

### TODO
- [ ] DB Lock 또는 대기열(Queue?) 방식 적용
- [ ] API 호출 시 동시성 검증 로직 추가
- [ ] 단위 테스트 작성

### 개발공수
- 

### 결과물
- 동시성 제어 로직 및 테스트 코드
