### ISSUE TITLE
TASK 1 : 잔액 충전 API 개발

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#16]
# Issue : 잔액 충전 API
: 사용자의 잔액을 충전하고 잔액 상태를 반환

### TODO
- [ ] API 엔드포인트 정의
- [ ] 요청 파라미터 검증 (사용자 ID, 충전 금액)
- [ ] 데이터베이스 업데이트 로직 구현
- [ ] 단위 테스트 작성

### 개발공수
- 

### 결과물
- 잔액 충전 API 및 테스트 코드
