### ISSUE TITLE
TASK 2 : 잔액 조회 API 개발

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#17]
# Issue : 잔액 조회 API
: 사용자의 현재 잔액 정보를 반환

### TODO
- [ ] API 엔드포인트 정의 (GET)
- [ ] 사용자 인증 및 요청 검증 로직 추가
- [ ] 데이터베이스에서 잔액 조회 로직 구현
- [ ] 단위 테스트 작성

### 개발공수
- 

### 결과물
- 잔액 조회 API 및 테스트 코드
