### ISSUE TITLE
TASK 3 : 결제 요청 및 승인 API 개발

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#18]
# Issue : 결제 요청 및 승인 API
: 결제 요청을 처리하고 잔액을 차감

### TODO
- [ ] API 엔드포인트 정의
- [ ] 요청 파라미터 검증 (사용자 ID, 좌석 ID, 결제 금액)
- [ ] 잔액 차감 (및 좌석 소유권 할당 로직 구현????)
- [ ] 데이터베이스 업데이트 및 결제 이력 저장
- [ ] 단위 테스트 작성

### 개발공수
- 

### 결과물
- 결제 API 및 테스트 코드
