### ISSUE TITLE
TASK 1 : 사용자 토큰 발급 API 개발

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#19]
# Issue : 사용자 토큰 발급 API
: 대기열에 등록된 사용자에게 고유 토큰을 발급

### TODO
- [ ] API 엔드포인트 정의
- [ ] 사용자 식별 및 대기열 등록 로직 구현
- [ ] 토큰 생성 및 만료 로직 구현
- [ ] 단위 테스트 작성

### 개발공수
- 

### 결과물
- 사용자 토큰 발급 API 및 테스트 코드
