### ISSUE TITLE
TASK1 : 시나리오별 요구사항 분석

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#2]
# Issue: 시나리오별 요구사항 분석

## TODO
- [ ] 시나리오별 주요 플로우 및 데이터 흐름 정의
- [x] 시퀀스 다이어그램 작성
- [x] 주요 프로세스에 대한 플로우 차트 작성

## 공수
- 1 M/D

## 결과물
- 요구사항 분석 문서
- 시각적 자료 (시퀀스 다이어그램 및 플로우 차트 등)
