### ISSUE TITLE
TASK 2 : 대기열 관리 로직 개발

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#20]
# Issue : 대기열 관리 로직
: 사용자의 대기 순서를 관리하고 요청 검증 시 순서 확인

### TODO
- [ ] 대기열 등록 및 순서 관리 로직 구현
- [ ] API 호출 시 대기열 확인 로직 추가
- [ ] 단위 테스트 작성

### 개발공수
- 

### 결과물
- 대기열 관리 로직 및 테스트 코드
