### ISSUE TITLE
TASK3 : ERD 설계

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#3]
# Issue: ERD 설계

## TODO
- [ ] 주요 엔티티와 속성 정의
- [ ] 엔티티 간 관계 설계
- [ ] ERD 다이어그램 작성

## 공수
- 1 M/D

## 결과물
- ERD 다이어그램
