### ISSUE TITLE
TASK4 : Mock API 작성

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#4]
# Issue: Mock API 작성
: 초기 데이터 흐름 테스트 및 클라이언트-서버 간 통신 시뮬레이션 돌려보기

## TODO
- [ ] API 요청(Request) 및 응답(Response) 샘플 작성
- [ ] Mock 데이터 생성 및 샘플 응답 구조 설계
- [ ] API 명세와 일치하도록 샘플 구현

## 공수
- 1 M/D

## 결과물
- Mock API 문서 (샘플 데이터 포함?)
- Postman 데이터(샘플) 파일
