### ISSUE TITLE
M2 : 예약 가능 날짜 및 좌석 조회 API

### ISSUE THREAD

**Issue by Yeon6v6** [Yeon6v6/HH99-ConcertReservation#5]
# Issue: 예약 가능 날짜 및 좌석 조회 구현
: 예약 가능한 날짜와 좌석을 반환하는 API

## TODO
- [ ] 예약 가능한 날짜 조회 API 개발
- [ ] 특정 날짜의 좌석 상태 조회 API 개발
- [ ] 데이터베이스 연동 및 데이터 검증 로직 구현
- [ ] 단위 테스트 작성 및 검증

## 공수
- 2~3 M/D

## 결과물
- 날짜 및 좌석 조회 API
- 테스트 코드
